function MG_out =  AddObjFunction( MG )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

MG.f = [ ...
    MG.price.UG_in', MG.price.UG_out', zeros(1,MG.horizon*MG.numofUG), ...
    MG.price.CL_in', MG.price.CL_out', zeros(1,MG.horizon*MG.numofCL), ...
    MG.price.ES_in', MG.price.ES_out', zeros(1,MG.horizon*MG.numofES), ...
    zeros(1,MG.horizon*MG.numofEV),zeros(1,MG.horizon*MG.numofEV),zeros(1,MG.horizon*MG.numofEV), ...
    zeros(1,MG.horizon*MG.numofRE), ...
    zeros(1,MG.horizon*MG.numofL0), ...
    zeros(1,MG.horizon*MG.numofL1), ...
    zeros(1,MG.horizon*MG.numofL2), zeros(1, MG.numofL2*(MG.horizon+1)), zeros(1, MG.numofL2*(MG.horizon+1)) ] ...
    .*MG.timespan ;

MG_out = MG;
end

